import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-background overflow-y-scroll"
        suppressHydrationWarning={true}
      >
        <div className="flex">
          <div className="sticky top-0 h-screen overflow-y-auto">
            <Sidebar />
          </div>
          <div className="flex-1 p-4 overflow-y-auto">
            <div className="">{children}</div>
            {/* <Footer /> */}
          </div>
        </div>
      </body>
    </html>
  );
}
