import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        suppressHydrationWarning={true}
        style={{ overflow: "hidden" }}
      >
        <div className="container h-screen bg-slate-800">
          <Navbar />
          <div className="flex flex-row gap-5">
            <div className="">
              <Sidebar />
            </div>
            <div className="flex-grow h-[85vh] p-5 bg-white rounded-2xl overflow-clip">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
